//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.17 at 11:39:41 AM EET 
//

package org.tempuri.purchaseorderschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.tempuri.purchaseorderschema package.
 * <p>
 * An ObjectFactory allows you to programmatically construct new instances of
 * the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the
 * binding of schema type definitions, element declarations and model groups.
 * Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _PurchaseOrder_QNAME = new QName("http://tempuri.org/PurchaseOrderSchema.xsd",
			"PurchaseOrder");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.tempuri.purchaseorderschema
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link PurchaseOrderType }
	 * 
	 */
	public PurchaseOrderType createPurchaseOrderType() {
		return new PurchaseOrderType();
	}

	/**
	 * Create an instance of {@link USAddress }
	 * 
	 */
	public USAddress createUSAddress() {
		return new USAddress();
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link PurchaseOrderType }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://tempuri.org/PurchaseOrderSchema.xsd", name = "PurchaseOrder")
	public JAXBElement<PurchaseOrderType> createPurchaseOrder(PurchaseOrderType value) {
		return new JAXBElement<PurchaseOrderType>(_PurchaseOrder_QNAME, PurchaseOrderType.class, null, value);
	}

}
