package suncertify.db.server;

/**
 * Defines a listener for events generated by an instance of
 * {@link NetworkService}.
 * 
 * @author Mohammad S. Abdellatif
 * @see NetworkService
 */
public interface NetworkServiceEventListener {

	/**
	 * Notification when a network service is started.
	 * 
	 * @param event
	 *            network service starting event.
	 */
	public void serviceStarted(NetworkServiceEvent event);

	/**
	 * Notification when a network service is stopped.
	 * 
	 * @param event
	 *            network service stop event.
	 */
	public void serviceStopped(NetworkServiceEvent event);
}
